New Folder/studyblu/studyblu/base/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('login/', views.login_user, name='login'),
    path('chatbot/', views.ai, name="chatbot"),
    
    path('logout/', views.logout_user, name='logout'),
    path('register/', views.register_user, name='register'),
    path('', views.index, name='index'),
    path('room/<str:pk>', views.home, name='home'),
    path('unread_notif/', views.unread_notif, name='unread_notif'),
    path('mark_read/', views.mark_read, name='mark_read'),
    path('create-room/', views.create_room, name='create-room'),
    path('update-room/<str:pk>', views.update_room, name='update-room'),
    path('delete-room/<str:pk>', views.delete_room, name='delete-room'),
    path('delete-message/<str:pk>', views.user_delete, name='delete-message'),
    path('delete-user/<str:pk>', views.delete_account, name='delete-account'),
    path('profile/<str:pk>', views.user_profile, name='profile-page'),
    path('account-info/<str:pk>', views.account_info, name='acount-info'),
    path('edit-user/', views.edit_user, name='edit-user'),
    path('settings/', views.settings, name='settings'),
    path('topics/', views.topics, name='topics'),
    path('activity/', views.activity, name='activity'),
    path('report/', views.report, name='report'),
    path('about/', views.about, name="about"),

   #light theme

   
]



New Folder/studyblu/studyblu/studybot/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('base/', include('base.urls')),
    path('mode/', include('base.urls_2')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

New Folder/studyblu/studyblu/base/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.core.exceptions import ValidationError

class User(AbstractUser):
    
    name=models.CharField(max_length=50, null=True)
    email=models.EmailField(unique=True, null=True)
    about=models.TextField(max_length=300, null=True, blank=True)
    avatar=models.ImageField(null=True, default='avatar.svg')
    
    REQUIRED_FIELDS=[]

class Topic(models.Model):
    name=models.CharField(max_length=100)
    
    def __str__(self):
        return self.name

class Room(models.Model):
    host=models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    topic=models.ForeignKey(Topic,  on_delete=models.SET_NULL, null=True)
    title=models.CharField(max_length=100)
    participants=models.ManyToManyField(User, related_name='participants', blank=True)
    
    
    description=models.TextField(null=True, blank=True)
    rules=models.TextField(null=True, blank=True)
    updated=models.DateTimeField(auto_now=True)
    created=models.DateTimeField(auto_now_add=True)
    
    class Meta():
        ordering=["-updated","-created"]
    
    def __str__(self):
        return self.title
    
def file_size(value):
    filesize=value.size
    if filesize > 50*1024*1024:
        raise ValidationError('The maximum file sixe that can be uploaded is 50MB')

    
class Message(models.Model):
    user=models.ForeignKey(User, on_delete=models.CASCADE)
    room=models.ForeignKey(Room,  on_delete=models.CASCADE)
    body=models.TextField()
    files=models.FileField( default=None, blank=True, max_length=5248280000 ,validators=[file_size])
    image=models.ImageField(null=True, default=None, max_length=5*1024*1024)
    updated=models.DateTimeField(auto_now=True)
    created=models.DateTimeField(auto_now_add=True)
    is_read=models.BooleanField(default=False)
    class Meta():
        ordering=["-updated","-created"]
    
    def __str__(self):
        return self.body[:50]
    
class Report(models.Model):
    email=models.EmailField(null=True)
    username=models.CharField(max_length=50, null=True)
    subject=models.CharField(max_length=300, null=True)
    body=models.TextField(null=False)
    
    
    updated=models.DateTimeField(auto_now=True)
    created=models.DateTimeField(auto_now_add=True)
    is_read=models.BooleanField(default=False)
    class Meta():
        ordering=["-updated","-created"]
    
    def __str__(self):
        return self.body[:50]
        

class Add(models.Model):
    join=models.ForeignKey(User, on_delete=models.CASCADE)
    updated=models.DateTimeField(auto_now=True)
    created=models.DateTimeField(auto_now_add=True)
      
       
    class Meta():
            ordering=["-updated","-created"]
    
    def __str__(self):
        return self.body[:50]



    
    

New Folder/studyblu/studyblu/templates/about.html
{% extends 'main.html'%}

{% block content%}
 {%load static%}

    <style>
    
        * {
            margin: 0;
            padding: 0;
            box-sizing: border-box;
        }

   
    

        .me{
            width: 25%;
            height: 5vh;
            float:right;
            margin: 5px;
            padding-left: 2px;
            text-align: center;
            color: aqua;
            text-shadow: rgb(32, 52, 63), 5px ;
        
        
        }

        .containers{
            position: relative;
            width: 45rem;
            height: 90rem;
            background: #f5f5f5; 
            box-shadow: 0 30px 50px #dbdbdb;
            border-radius:9%;
            
            
            
        }

        .containers .slide .item{
            width: 100px;
            height: 160px;
            position:absolute;
            top: 50%;
            left:75%;
            transform: translate(0, -50%);
            border-radius: 20px;
            box-shadow:0 30px 50px #505050 ;
            background-position: 50% 50%;
            background-size: cover;
            display: inline-block;
            transition: 0.5s;
            
            }

        .slide .item:nth-child(1),
        .slide .item:nth-child(2){
            top: 0;
            left:0;
            transform: translate(0, 0);
            
            width: 100%;
            height: 100%;
            border-radius:9%;
        }

       

       

        .item .content{
            position: absolute;
            top: 30%;
            right:100px;
            width: 300px;
            text-align: left;
            color: #eee;
            transform: translate(0, 50%);
            font-family: system-ui, -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, 'Open Sans', 'Helvetica Neue', sans-serif;
            display: none;
            border-radius:9%;
        }



        .slide .item:nth-child(2) .content{
            display: block;
        }

        .content .name{
            font-size: 40px;
            text-transform: uppercase;
            font-weight: bold;
            opacity: 0;
            animation: animate 1s ease-in-out 1 forwards;
            color:skyblue;
        }

        .content .des{
            margin-top: 5px;
            margin-bottom: 10px;
            opacity: 0;
            animation:  animate 1s ease-in-out 0.3s 1 forwards;
            color:rgb(54, 157, 197);
        }

        .content .button{
            padding: 10px 20px;
            border: none;
            cursor: pointer;
            opacity: 0;
            animation: animate 1s ease-in-out 0.6s 1 forwards ;
        }

        @keyframes animate{
            from{
                opacity: 0;
                transform: translate(0, 100px);
                filter: blur(33px);
            }
            to{
                opacity: 1;
                transform: translate(0);
                filter: blur(0);
            }
        }
        .button{
            width: 100%;
            text-align: center;
            position: absolute;
            bottom: 20px;


        }

        .button button{
            width: 40px;
            height: 35px;
            border-radius: 8px;
            border: none;
            cursor: pointer;
            margin: 0 5px;
            border: 1px solid #000;
            transition: 0.3s;
            background-color: antiquewhite;
        }

        button:hover{
            background: rgb(64, 74, 78);
            color: #fff;
        }
        button:active{
            opacity: 0.5;
        }


    </style>

    
        {% comment %} <div class="me">
            <div class="room__topics">
                RAHIMSTUDIOS.LTD
            
                    <div class="contact-details col-md-6 ">
                        <h3 class="mb-3">Contact Details</h3>
                        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ipsam, vero, provident, eum eligendi blanditiis ex
                            explicabo vitae nostrum facilis asperiores dolorem illo officiis ratione vel fugiat dicta laboriosam labore
                            adipisci.</p>
                        <ul class="contact-short-info mt-4">
                            <li class="mb-3">
                                <i class="tf-ion-ios-home"></i>
                                <span>Khaja Road, Bayzid, Chittagong, Bangladesh</span>
                            </li>
                            <li class="mb-3">
                                <i class="tf-ion-android-phone-portrait"></i>
                                <span>Phone: +880-31-000-000</span>
                            </li>
                            <li class="mb-3">
                                <i class="tf-ion-android-globe"></i>
                                <span>Fax: +880-31-000-000</span>
                            </li>
                            <li>
                                <i class="tf-ion-android-mail"></i>
                                <span>Email: hello@meghna.com</span>
                            </li>
                        </ul>
                        <!-- Footer Social Links -->
                        <div class="social-icon">
                            <ul>
                                <li><a href="https://themefisher.com/"><i class="tf-ion-social-facebook"></i></a></li>
                                <li><a href="https://themefisher.com/"><i class="tf-ion-social-twitter"></i></a></li>
                                <li><a href="https://themefisher.com/"><i class="tf-ion-social-dribbble-outline"></i></a></li>
                                <li><a href="https://themefisher.com/"><i class="tf-ion-social-linkedin-outline"></i></a></li>
                            </ul>
                        </div>
                        <!--/. End Footer Social Links -->
                    </div>
            </div>
        
                
        </div> {% endcomment %}
    
   <div class="containers">
    <div class="slide" >
        <div class="item" style="background-image:url({% static "images/team/p1.jpg" %});">
            <div class="content">
                <div class="name">Ibrahim Fonyuy</div>
                <div class="des">The only aspect which distinguishes a leader from a follower is the art of creativity (innovation)</div>
                <div class="des">Backend Developer</div>
                <button>see more</button>
            </div>
        </div>
        
        <div class="item" style="background-image:url({% static "images/team/p3.jpg" %});">
            <div class="content">
                <div class="name">Ngochu Emanuella</div>
                <div class="des">An emerging instance of development and advanced facilities which has powerfull reasoning often compared to humans </div>
                <div class="des">Frontend Developer</div>
                <button>see more</button>
            </div>
        </div>
        <div class="item" style="background-image:url({% static "images/team/p4.jpg" %});">
            <div class="content">
                <div class="name">Ndi Kelvin</div>
                <div class="des">Lear More Do More Be Better</div>
                <div class="des">Backend Developer</div>
                <button>see more</button>
            </div>
        </div>
       
        <div class="button">
            <button class="prev">prev
                <i class="fa-solid fa-arrow-left"></i>
            </button>
            <button class="next">next
                <i class="fa-solid fa-arrow-right"></i>
            </button>
        </div>
    </div>
   </div>
   
    


    <script>
        const $next =  document.querySelector('.next');
        const $prev =  document.querySelector('.prev');

        $next.addEventListener(
            'click',
            () => {
                const items = document.querySelectorAll('.item');
                document.querySelector('.slide').appendChild(items[0]);

            },
            
        );

        $prev.addEventListener(
            'click',
            () => {
                const items = document.querySelectorAll('.item');
                document.querySelector('.slide').prepend(items[items.length - 1]);
            },
        );
    </script>
   
{%endblock content%}

New Folder/studyblu/studyblu/templates/account.html
  
{%extends 'main.html'%}

{% block content%}
  {% if request.user.is_authenticated%}
  {%if request.user == user%}
  
  <main class="profile-page layout layout--3">
    <div class="container">
      <!-- Topics Start -->
      <main class="create-room layout">
        <div class="container">
          <div class="layout__box">
            <div class="layout__boxHeader">
              <div class="layout__boxTitle">
                <a href="{{request.META.HTTP_REFERER}}">
                  <svg
                    version="1.1"
                    xmlns="http://www.w3.org/2000/svg"
                    width="32"
                    height="32"
                    viewBox="0 0 32 32"
                  >
                    <title>arrow-left</title>
                    <path
                      d="M13.723 2.286l-13.723 13.714 13.719 13.714 1.616-1.611-10.96-10.96h27.625v-2.286h-27.625l10.965-10.965-1.616-1.607z"
                    ></path>
                  </svg>
                </a>
                <h3>Acccount info</h3>
              </div>
            </div>
            <div class="room__topics">
              Name: {{user.name}}<br>
              Email: {{user.email}}<br>
              Username: {{user.username}}<br>
              About: {{user.about}}<br>
              Profile number: {{user.id}}<br>
              Number of rooms created: {{db.count}}<br>
              Messages send: {{room_messages.count}}<br>
              Status: loggedin<br>
              
              
              Password: {{user.password}}


      
      <!-- Topics End -->

      <!-- Room List Start -->
      

      <!-- Activities Start -->
      
      <!-- Activities End -->
    </div>
  </main>
  {%else%}
  <h1 style="color:red; text-align:center;">you are not allowed here 🛑</h1>
  {%endif%}
  {%endif%}
  

{%endblock content%}

New Folder/studyblu/studyblu/templates/activity.html
{%extends 'main.html'%}

{% block content%}
    <main class="layout">
      <div class="container">
        <div class="layout__box">
          <div class="layout__boxHeader">
            <div class="layout__boxTitle">
              <a href="{% url 'index'%}">
                <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
                  <title>arrow-left</title>
                  <path
                    d="M13.723 2.286l-13.723 13.714 13.719 13.714 1.616-1.611-10.96-10.96h27.625v-2.286h-27.625l10.965-10.965-1.616-1.607z"
                  ></path>
                </svg>
              </a>
              <h3>Recent Activities</h3>
            </div> 
          </div>

          <div class="activities-page layout__body">
            {% for message in room_messages%}
            <div class="activities__box">
              <div class="activities__boxHeader roomListRoom__header">
               
                <a href="{% url 'profile-page' message.user.id %}" class="roomListRoom__author">
                  <div class="avatar avatar--small">
                    <img src="{{message.user.avatar.url}}" />
                  </div>
                  <p>
                    @{{message.user.username}}
                    <span>{{message.created|timesince}}</span>
                  </p>
                </a>
              
               
                {% if request.user  == message.user %}
                <div class="roomListRoom__actions">
                  <a href="{% url 'delete-message' message.id %}">
                    <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
                      <title>remove</title>
                      <path
                        d="M27.314 6.019l-1.333-1.333-9.98 9.981-9.981-9.981-1.333 1.333 9.981 9.981-9.981 9.98 1.333 1.333 9.981-9.98 9.98 9.98 1.333-1.333-9.98-9.98 9.98-9.981z"
                      ></path>
                    </svg>
                  </a>
                </div>
                {%endif%}
              </div>
             
              
              <div class="activities__boxContent">
                <p>replied to post “<a href="{% url 'home' message.room.id %}">{{message.room}}</a>”</p>
                <div class="activities__boxRoomContent">
                  {{message.body}}..
                </div>
              </div>
            </div>
            {%endfor%}
               
          </div>
        </div>
      </div>
    </main>

    <script src="script.js"></script>

{%endblock content%}

New Folder/studyblu/studyblu/templates/delete.html
{% extends 'main.html'%}


{% block content%}


    <main class="delete-item layout">
        <div class="container">
            <div class="layout__box">
                <div class="layout__boxHeader">
                    <div class="layout__boxTitle">
                        <a href="{{request.META.HTTP_REFERER}}">
                            <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32"
                                viewBox="0 0 32 32">
                                <title>arrow-left</title>
                                <path
                                    d="M13.723 2.286l-13.723 13.714 13.719 13.714 1.616-1.611-10.96-10.96h27.625v-2.286h-27.625l10.965-10.965-1.616-1.607z">
                                </path>
                            </svg>
                        </a>
                        <h3>Back</h3>
                    </div>
                </div>
                <div class="layout__body">
                    <form class="form" action="" method="POST">
                        {%csrf_token%}
                        <div class="form__group">
                            <p>Are you sure you want to delete "{{obj}}"?</p>
                        </div>

                        <div class="for__group">
                            <input class="btn btn--main" type="submit" value="Confirm" />
                        </div>

                    </form>
                </div>
            </div>
        </div>
    </main>
    <script src="script.js"></script>
{%endblock content%}

New Folder/studyblu/studyblu/templates/delete_old.html
{% extends 'main.html'%}


{%block content%}
<form method="POST" action="">
    {% csrf_token%}
    <h3> are you sure you want to delete "{{obj}}"?</h3>
    <a href="{{request.META.HTTP_REFERER}}">Go back</a>
    <input type="submit" value="confirm">
</form>


{%endblock content%}


New Folder/studyblu/studyblu/templates/home.html
{% extends "main.html" %}

{%block content%}
    <main class="layout layout--3">
      <div class="container">
        

        <!-- Topics Start -->
        {% include 'base/topics_components.html' %}
      
        <!-- Topics End -->

        <!-- Room List Start -->
        <div class="roomList">
          <div class="mobile-menu">
            
            <form action="{% url 'index'%}" class="header__search" method="GET">
              <label>
                <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
                  <title>search</title>
                  <path
                    d="M32 30.586l-10.845-10.845c1.771-2.092 2.845-4.791 2.845-7.741 0-6.617-5.383-12-12-12s-12 5.383-12 12c0 6.617 5.383 12 12 12 2.949 0 5.649-1.074 7.741-2.845l10.845 10.845 1.414-1.414zM12 22c-5.514 0-10-4.486-10-10s4.486-10 10-10c5.514 0 10 4.486 10 10s-4.486 10-10 10z"
                  ></path>
                </svg>
                <input name="q" placeholder="Search for posts" />
                <button class="btn" type="submit">search</button>
              </label>
            </form>
            {%if request.user.is_authenticated%}
            <div style="margin-bottom:2%; text-align:center; "><h1>HELLO</h1><h1 style="color:skyblue;"> {{request.user.username}}</h1></div>
            <h1 style="margin-bottom:2%; text-align:center;">WE'VE BEEN WAITING FOR YOU</h1>
            
            <h1 style="text-align: center; color:skyblue; margin-bottom:4%;">WELCOME TO THIS LEARNING SITE WHERE YOU INCREASE YOUR TECH KNOWLEGDE TO THE PEAK</h1>
            {%endif%}
            <div class="mobile-menuItems">
              <a class="btn btn--main btn--pill" href="{%url 'topics' %}">Browse Topics</a>
              <a class="btn btn--main btn--pill" href="{%url 'activity' %}">Recent Activities</a>
            </div>
          </div> 
          <div class="roomList__header">
            <div>
              <h2>Study Rooms</h2>
              {% if q %}
              <p>{{room_count}} Room(s) available for {{q}}</p>
              {%else%}
              <p>{{room_count}} Room(s) available</p>
              {%endif%}
              
            </div>
            {%for message in messages%}
              <span style="color:green; text-align:center;">{{message}}</span>
              {%endfor%}
            <a class="btn btn--main" href="{% url 'create-room' %}">
              <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
                <title>add</title>
                <path
                  d="M16.943 0.943h-1.885v14.115h-14.115v1.885h14.115v14.115h1.885v-14.115h14.115v-1.885h-14.115v-14.115z"
                ></path>
              </svg>
              Create Room
            </a>
          </div>
          {% include 'base/feed_components.html' %}
        </div>
        <!-- Room List End -->

        <!-- Activities Start -->
        {% include 'base/activity_component.html' %}
      
        <!-- Activities End -->
      </div>
    </main>

{%endblock content%}

New Folder/studyblu/studyblu/templates/main.html
<!DOCTYPE html>
<html lang="en">
{% load static %}
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="shortcut icon" href="assets/favicon.ico" type="image/x-icon" />
    <link rel="stylesheet" href="{%  static 'styles/style.css' %}" />
    <title>StudyBlu - Revolutionilizing Education through innovative learning</title>

    <style>

      #preloader {
        background: rgb(22, 23, 43);
        height: 100%;
        left: 0;
        opacity: 1;
        filter: alpha(opacity=100);
        position: fixed;
        text-align: center;
        top: 0;
        width: 100%;
        z-index: 999999999;
      }
      
       
      .container_load{
        display: flex;
        justify-content: center;
        align-items: center;
        position: relative;
        padding-top: 20%;
      }

      .text{
        color: rgb(54, 157, 197);
        font-family: sans-serif;
        text-shadow: white;
        font-weight: bolder;
        font-size:25px;

      }
      .ring{
        position: absolute;
        width: 200px;
        height: 190px;
        border: 1px solid transparent;
        border-radius: 50%;
        --color:#ff8df9;
        border-bottom: 10px solid var(--color);
        animation: rotate1 2s linear infinite;
      }

      @keyframes rotate1 {
        from {
        transform: rotateX(100deg) rotateZ(200deg);
        }

        to {
        transform: rotateX(100deg) rotateZ(940deg);
        }

            
      }
        
      .ring:nth-child(2){
        --color:red;
        animation-name: rotate2;

      }

      @keyframes rotate2 {
            from {
                transform: rotateX(100deg) rotateY(50deg) rotateZ(200deg);
            }

            to {
                transform: rotateX(100deg) rotateY(50deg) rotateZ(940deg);
            }

            
      }

      .ring:nth-child(3){
        --color:blue;
        animation-name: rotate3;

      }

      @keyframes rotate3 {
            from {
                transform: rotateX(100deg) rotateY(130deg) rotateZ(900deg);
            }

            to {
                transform: rotateX(100deg) rotateY(130deg) rotateZ(180deg);
            }

            
      }

    

    </style>   
    
  </head>

  <body>

     <div id="preloader">
      <div class="container_load">
          <div class="ring"></div>
          <div class="ring"></div>
          <div class="ring"></div>
          <div class="ring"></div>
          <div class="text"><span style="color:white;">STUDY</span>BLU</div>
      </div>
    </div>      
    


    {% include 'navbar.html'%}
    {%if messages%}
    <ul class="messages">
        {% for message in messages%}
    {{message}}
        {%endfor%}
    </ul>
    {%endif%}


    {% block content %}

    {% endblock %}

    

    <!-- 
    Essential Scripts
    =====================================-->
    <!-- Main jQuery -->


    <script src="{% static 'plugins/jquery/jquery.min.js'%}"></script>

    <!-- Bootstrap4 -->
    <script src="{% static 'plugins/bootstrap/bootstrap.min.js' %}"></script>
    <!-- Parallax -->
    <script src="{% static 'plugins/parallax/jquery.parallax-1.1.3.js' %}"></script>
    <!-- lightbox -->
    <script src="{% static 'plugins/lightbox2/js/lightbox.min.js'%}"></script>
    <!-- Owl Carousel -->
    <script src="{% static 'plugins/slick/slick.min.js'%}"></script>
    <!-- filter -->
    <script src="{% static 'plugins/filterizr/jquery.filterizr.min.js'%}"></script>
    <!-- Smooth Scroll js -->
    <script src="{% static 'plugins/smooth-scroll/smooth-scroll.min.js'%}"></script>
    <!-- Google Map -->
    <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCcABaamniA6OL5YvYSpB3pFMNrXwXnLwU"></script>
    <script src="{% static 'plugins/google-map/gmap.js' %}"></script>  


    <script src="{% static 'js/script.js' %}"></script>
  </body>
</html>

New Folder/studyblu/studyblu/templates/profile.html
{%extends 'main.html'%}

{% block content%}
  <main class="profile-page layout layout--3">
    <div class="container">
      <!-- Topics Start -->
      {% include 'base/topics_components.html' %}
      <!-- Topics End -->

      <!-- Room List Start -->
      <div class="roomList">
        <div class="profile">
          <div class="profile__avatar">
            <a href="{{user.avatar.url}}"><div class="avatar avatar--large active">
              <img src="{{user.avatar.url}}" />
            </div></a>
          </div>
          <div class="profile__info">
            <h3>{{user.name}}</h3>
           
            <p>@{{user.username}}</p>
            {% if request.user == user%}
            <a href="{% url 'edit-user' %}" class="btn btn--main btn--pill">Edit Profile</a><br>
            <a href="{% url 'settings' %}" style="margin-top:5px;"class="btn btn--main btn--pill">Settings</a><br>
            
          
            {%endif%}
          </div>
          <div style="text-align:center;" class="profile__about">
            <h3>About</h3>
            <p>
             {{user.about}}
            </p>
            {%for message in messages%}
              <span style="color:green;">{{message}}</span>
              {%endfor%}
          </div>
        </div>

        <div class="roomList__header">
          {%if request.user != user%}
          <div>
            <h2>Study Rooms Hosted by {{user.username}}</a>
            </h2>
          </div>
          {%else%}
          <div>
            <h2>Study Rooms Hosted by you</a>
            </h2>
          </div>
          {%endif%}
        </div>
       
        {%include 'base/feed_components.html'%}

      

        
      </div>
      <!-- Room List End -->

      <!-- Activities Start -->
      {%include 'base/activity_component.html'%}
      <!-- Activities End -->
    </div>
  </main>

{%endblock content%}

New Folder/studyblu/studyblu/templates/topics.html
{%extends 'main.html'%}

{% block content%}
    <main class="create-room layout">
      <div class="container">
        <div class="layout__box">
          <div class="layout__boxHeader">
            <div class="layout__boxTitle">
              <a href="{%url 'index' %}">
                <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
                  <title>arrow-left</title>
                  <path
                    d="M13.723 2.286l-13.723 13.714 13.719 13.714 1.616-1.611-10.96-10.96h27.625v-2.286h-27.625l10.965-10.965-1.616-1.607z"
                  ></path>
                </svg>
              </a>
              <h3>Browse Topics</h3>
            </div>
          </div>

          <div class="topics-page layout__body">
            <form class="header__search" method="GET" action="{%url 'index'%}" >
              <label>
                <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
                  <title>search</title>
                  <path
                    d="M32 30.586l-10.845-10.845c1.771-2.092 2.845-4.791 2.845-7.741 0-6.617-5.383-12-12-12s-12 5.383-12 12c0 6.617 5.383 12 12 12 2.949 0 5.649-1.074 7.741-2.845l10.845 10.845 1.414-1.414zM12 22c-5.514 0-10-4.486-10-10s4.486-10 10-10c5.514 0 10 4.486 10 10s-4.486 10-10 10z"
                  ></path>
                </svg>
                <input name='q' placeholder="Search for posts" />
                
              </label>
            </form>

            <ul class="topics__list">
              <li>
                <a href="{% url 'index' %}" class="active">All<span>{{topics.count}}</span></a>
              </li>
              {% for topic in topics %}
              <li>
                <a href="{% url 'index' %}?q={{topic.name}}">{{topic.name}}<span>{{topic.room_set.all.count}}</span></a>
              </li>
              {%endfor%}
            
              </li>
            </ul>
          </div>
        </div>
      </div>
    </main>

    <script src="script.js"></script>
 

{%endblock content%}